language: haskell

matrix:
  allow_failures:
    - env: GHCVER=head
    - env: GHCVER=7.0.4
    - env: GHCVER=7.2.2
    - env: GHCVER=7.4.2
    - env: GHCVER=7.6.3
    - env: GHCVER=7.8.1

env:
 - GHCVER=head
 - GHCVER=7.0.4
 - GHCVER=7.2.2
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - travis_retry cabal-1.18 install --only-dependencies
 - cabal-1.18 install --enable-tests

script:
 - echo "All done."
