sudo: false

language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

matrix:
  include:
    - env: RESOLVER=lts-9.12
    # for GHC 8.0.2
    - env: RESOLVER=lts-7.24
    # for GHC 8.0.1
    - env: RESOLVER=lts-6.35
    # for GHC 7.10.3
    - env: RESOLVER=lts-3.22
    #for GHC 7.10.2
    - env: RESOLVER=lts-2.22
    #for GHC 7.8.4

install:
  - stack --resolver $RESOLVER --no-terminal setup

script:
  - stack --resolver $RESOLVER --no-terminal build
  - stack --resolver $RESOLVER --no-terminal test
  - bash  testit.sh
  - stack --resolver $RESOLVER --no-terminal exec -- cabal check
  - stack --resolver $RESOLVER --no-terminal exec -- cabal sdist
  # Check that the resulting source distribution can be built & installed.
  # If there are no other `.tar.gz` files in `dist`, this can be even simpler:
  # `cabal install --force-reinstalls dist/*-*.tar.gz`
  - SRC_TGZ=$(stack exec -- cabal info . | awk '{print $2;exit}').tar.gz &&
    (cd dist && stack --resolver $RESOLVER install --force-reinstalls "$SRC_TGZ")

# EOF
